name: Test Component

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Cache Angular Webpack
        uses: actions/cache@v2
        with:
          path: .angular
          key: ${{ runner.OS }}-angular-webpack-${{ hashFiles('**/package-lock.json') }}

      - name: Install Global Packages
        run: npm i -g @angular/cli

      - name: Install Packages
        run: npm i --legacy-peer-deps

      - name: Test
        run: npm run test:ci

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Cache Angular Webpack
        uses: actions/cache@v2
        with:
          path: .angular
          key: ${{ runner.OS }}-angular-webpack-${{ hashFiles('**/package-lock.json') }}

      - name: Install Global Packages
        run: npm i -g @angular/cli

      - name: Install Packages
        run: npm i --legacy-peer-deps

      - name: Build
        run: npm run build
