name: Test Component

on:
  push:
    tags-ignore:
      - "**" # Ignore tags
  pull_request:
    types:
      - opened
      - reopened

concurrency:
  group: cal-ci-${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Global Packages
        run: npm i -g @angular/cli

      - name: Install Packages
        run: npm i

      - name: Test
        run: npm run test:ci

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Global Packages
        run: npm i -g @angular/cli

      - name: Install Packages
        run: npm i

      - name: Build
        run: npm run build
