name: Test Component

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened

concurrency:
  group: cal-ci-${{ github.ref }}-test
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install Global Packages
        run: yarn global add @angular/cli

      - name: Install Packages
        run: yarn

      - name: Test
        run: npm run test:ci

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install Global Packages
        run: yarn global add @angular/cli

      - name: Install Packages
        run: yarn

      - name: Build
        run: npm run build
